// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7I0mGe3A_rNgRfBuRuUHjhJmTjjVCLCk',
    appId: '1:374661744245:web:2eccfd84cd27839f8fda3c',
    messagingSenderId: '374661744245',
    projectId: 'chat-app-c9b2d',
    authDomain: 'chat-app-c9b2d.firebaseapp.com',
    storageBucket: 'chat-app-c9b2d.appspot.com',
    measurementId: 'G-VFJ4C49MGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLWtGAMHF1IqLgdXAuZ7XCG-SiOUORlZw',
    appId: '1:374661744245:android:c200e95c49e5d3cb8fda3c',
    messagingSenderId: '374661744245',
    projectId: 'chat-app-c9b2d',
    storageBucket: 'chat-app-c9b2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx5Q4I_rcRAfyhPpYZzYNcIGAdp_NM3xU',
    appId: '1:374661744245:ios:1832bbf7322e6b428fda3c',
    messagingSenderId: '374661744245',
    projectId: 'chat-app-c9b2d',
    storageBucket: 'chat-app-c9b2d.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

}